#!/bin/sh
FLUXHOME=/home/ionflux
DISTDIR=$FLUXHOME/svn/iftools/trunk/iftools
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DISTDIR/lib
PATH=$PATH:$DISTDIR/bin
PYTHONPATH=$PYTHONPATH:$DISTDIR/swig/python
export LD_LIBRARY_PATH PATH PYTHONPATH

